### ISSUE TITLE
[BUG] OutofMemory error in service-map pipeline

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#1021]
**Describe the bug**
The service-map pipeline continues to suffer from memory leak although it was previously tackled by https://github.com/opendistro-for-elasticsearch/data-prepper/pull/671. The issue needs to be revisited.

**To Reproduce**
1. pipeline definition:
```
entry-pipeline:
  source:
    otel_trace_source:
      ssl: false
      unframed_requests: true
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  prepper:
    - otel_trace_raw_prepper:
#        trace_flush_interval: 6
#    - otel_trace_group_prepper:
#        hosts: [ "https://node-0.example.com:9200" ]
#        username: "admin"
#        password: "admin"
  sink:
    - opensearch:
        hosts: [ "https://node-0.example.com:9200" ]
        username: "admin"
        password: "admin"
        trace_analytics_raw: true
service-map-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  prepper:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["https://node-0.example.com:9200"]
        username: "admin"
        password: "admin"
        trace_analytics_service_map: true
```
2. run data-prepper in docker with opensearch backend
3. run a load generator to send ExportTraceServiceRequest of batch size 20 to otel-trace-source.
4. See example error:
```
2022-02-09T19:21:07,474 [service-map-pipeline-prepper-worker-3-thread-1] ERROR com.amazon.dataprepper.pipeline.common.PipelineThreadPoolExecutor - Pipeline [service-map-pipeline] process worker encountered a fatal exception, cannot proceed further
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.amazon.dataprepper.pipeline.common.PipelineThreadPoolExecutor.afterExecute(PipelineThreadPoolExecutor.java:70) [data-prepper.jar:1.2.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1131) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.fasterxml.jackson.core.io.ContentReference.construct(ContentReference.java:101) ~[data-prepper.jar:1.2.1]
	at com.fasterxml.jackson.core.JsonFactory._createContentReference(JsonFactory.java:1990) ~[data-prepper.jar:1.2.1]
	at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1316) ~[data-prepper.jar:1.2.1]
	at com.fasterxml.jackson.databind.ObjectMapper.createGenerator(ObjectMapper.java:1188) ~[data-prepper.jar:1.2.1]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3822) ~[data-prepper.jar:1.2.1]
	at com.amazon.dataprepper.plugins.prepper.ServiceMapStatefulPrepper.lambda$iteratePrepperState$7(ServiceMapStatefulPrepper.java:235) ~[data-prepper.jar:1.2.1]
	at com.amazon.dataprepper.plugins.prepper.ServiceMapStatefulPrepper$$Lambda$907/0x000000080118bbe8.accept(Unknown Source) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at com.amazon.dataprepper.plugins.prepper.ServiceMapStatefulPrepper.iteratePrepperState(ServiceMapStatefulPrepper.java:207) ~[data-prepper.jar:1.2.1]
	at com.amazon.dataprepper.plugins.prepper.ServiceMapStatefulPrepper.evaluateEdges(ServiceMapStatefulPrepper.java:184) ~[data-prepper.jar:1.2.1]
	at com.amazon.dataprepper.plugins.prepper.ServiceMapStatefulPrepper.doExecute(ServiceMapStatefulPrepper.java:131) ~[data-prepper.jar:1.2.1]
	at com.amazon.dataprepper.model.prepper.AbstractPrepper.lambda$execute$0(AbstractPrepper.java:44) ~[data-prepper.jar:1.2.1]
	at com.amazon.dataprepper.model.prepper.AbstractPrepper$$Lambda$712/0x00000008010d3e10.get(Unknown Source) ~[?:?]
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:57) ~[data-prepper.jar:1.2.1]
	at com.amazon.dataprepper.model.prepper.AbstractPrepper.execute(AbstractPrepper.java:44) ~[data-prepper.jar:1.2.1]
	at com.amazon.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:62) ~[data-prepper.jar:1.2.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	... 2 more

```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by graytaylor0** [comment]
Are you able to run the Memory Profiler on this to see where the memory is getting used?

**Comment by graytaylor0** [comment]
Thanks for the background info. That is interesting. What rps did you get the `OutOfMemory` Error with? Is it possible that the `ServiceMap` just couldn't handle the load with the java heap space that was provided to it?

**Comment by chenqi0805** [comment]
Finally I have been able to reproduce Outofmemory in my local machine and do memory profiling in intellij:
* memory chart:
![Screen Shot 2022-02-14 at 2 22 56 PM](https://user-images.githubusercontent.com/19492223/153944524-eaf32ee7-027c-4cb5-98d7-c4576811f80f.png)

* Biggest objects breakdown:
![Screen Shot 2022-02-14 at 2 25 11 PM](https://user-images.githubusercontent.com/19492223/153944635-afa86c9c-42a4-4466-857a-13c45c8d1137.png)

From the above, there are two sources that lead to memory leak:

1. heapDB in mapdb
2. RELATIONSHIP_STATE concurrent hashset

**Comment by dlvenable** [comment]
Thanks @chenqi0805,

Regarding heapDB, this might be due to having too small a heap. Data Prepper administrators do need to set aside enough heap space for this. We might need to give guidance.

I took a brief look at `RELATIONSHIP_STATE`. I only see calls to `add`. So it will grow unbounded. I think we expect that the number of relationships is small enough to provide its a natural bound to growth. But, the presence of `traceGroupName` prevents that assumption from being valid. What is `traceGroupName` providing here?

**Comment by dlvenable** [comment]
Thanks @chenqi0805 for elaborating on the `RELATIONSHIP_STATE`.

Regarding the heapDB, I suspect that Data Prepper doesn't have a memory leak here since it completely clears the map when the window ends.

It seems that the real problem is that Data Prepper requires a lot of memory for these traces! I see two distinct solutions:
1. Improve the Data Prepper documentation with some guidance on memory usage, window duration, and the overall number of traces that teams expect to provide.
2. Investigate if Data Prepper needs to keep all the traces. Are there traces which are not exactly duplicates, but do not yield any additional information? If so, can they be removed? What impact would this have on throughput though?

**Comment by martialblog** [comment]
Hi, ran into the same issue whilst testing the `examples/jaeger-hotrod/docker-compose.yml`. 

I managed to get something running with a combination of `JAVA_OPTS=-Xms4G -Xmx4G` for the Data Prepper JVM and buffer configuration for the pipeline:

```
  buffer:
    bounded_blocking:
      buffer_size: 128
      batch_size: 256
```

The docs currently say:

> Configure the Data Prepper heap by setting the JVM_OPTS environment variable.

I think that is wrong and needs to be JAVA_OPTS.

With JVM_OPTS

```
bash-5.2$ jinfo 1 | grep args
jvm_args: -Dfile.encoding=UTF-8 -Dlog4j.configurationFile=/usr/share/data-prepper/config/log4j2-rolling.properties 
-Ddata-prepper.dir=/usr/share/data-prepper
```

With JAVA_OPTS

```
jvm_args: -Dfile.encoding=UTF-8 -Dlog4j.configurationFile=/usr/share/data-prepper/config/log4j2-rolling.properties 
-Xms4G -Xmx4G -Ddata-prepper.dir=/usr/share/data-prepper 
```

I'll open a PR to update the docs. Is there anything else that should be updated?
