### ISSUE TITLE
[BUG] Trace event processor does not work

### ISSUE THREAD

**Issue by dbason** [opensearch-project/data-prepper#1653]
**Describe the bug**
When using the event record type for tracing it throws an error in the processor
```
[raw-pipeline-processor-worker-5-thread-3] ERROR com.amazon.dataprepper.pipeline.ProcessWorker - Encountered exception during pipeline raw-pipeline processing
java.lang.ClassCastException: class io.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest cannot be cast to class com.amazon.dataprepper.model.trace.Span (io.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest and com.amazon.dataprepper.model.trace.Span are in unnamed module of loader 'app')
at com.amazon.dataprepper.plugins.processor.oteltrace.OTelTraceRawProcessor.doExecute(OTelTraceRawProcessor.java:77) ~[data-prepper.jar:1.4.0]
at com.amazon.dataprepper.model.processor.AbstractProcessor.lambda$execute$0(AbstractProcessor.java:55) ~[data-prepper.jar:1.4.0]
at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:61) ~[data-prepper.jar:1.4.0]
at com.amazon.dataprepper.model.processor.AbstractProcessor.execute(AbstractProcessor.java:55) ~[data-prepper.jar:1.4.0]
at com.amazon.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:62) ~[data-prepper.jar:1.4.0]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:832) ~[?:?]
```

**To Reproduce**
Deploy a standard tracing pipeline and send traces from otel collector
Pipeline configuration is
```yaml
entry-pipeline:
  workers : 8
  delay: "100"
  buffer:
    bounded_blocking:
      buffer_size: 4096
      batch_size: 160
  source:
    otel_trace_source:
      ssl: false
  sink:
  - pipeline:
      name: "raw-pipeline"
  - pipeline:
      name: "service-map-pipeline"
raw-pipeline:
  workers : 8
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 4096
      batch_size: 160
  processor:
  - otel_trace_raw:
  sink:
  - opensearch:
      hosts: ["host"]
      username: redacted
      password: redacted
      index: otel-v1-apm-span
      index_type: custom
service-map-pipeline:
  workers : 1
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
  - service_map_stateful:
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 8
  sink:
  - opensearch:
      hosts: ["host"]
      username: redacted
      password: redacted
      index: otel-v1-apm-service-map
      index_type: custom
```

**Expected behavior**
Pipeline should be successful

**Environment (please complete the following information):**
 - OS: Docker image running in kubernetes
 - Version: tried with 1.4.0 and 1.5.1

**Comment by chenqi0805** [comment]
@dbason Thanks for your interest in Data Prepper! The issue is that the record_type in otel_trace_source needs to be event for it to work with otel_trace_raw. Please refer to the documentation here: https://opensearch.org/docs/1.3/clients/data-prepper/data-prepper-reference/#otel_trace_raw

Alternatively, you can retreat to use otel_trace_raw_prepper with your current otel_trace_source setting but just a reminder it is not going to be supported in 2.0 release.

**Comment by dlvenable** [comment]
The work in #1272 will remove the deprecated record type. As @chenqi0805 noted this is planned for 2.0 in September.

**Comment by dbason** [comment]
Argh, not sure how I missed this.  Thanks for the fix.
