### ISSUE TITLE
[BUG] AWS services fail to load

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1876]
**Describe the bug**

Running the current `main` branch (for 2.0), the OpenSearch sink will not write to an Amazon OpenSearch Service domain.

```
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Multiple HTTP implementations were found on the classpath. To avoid non-deterministic loading implementations, please explicitly provide an HTTP client via the client builders, set the software.amazon.awssdk.http.service.impl system property with the FQCN of the HTTP service to use as the default, or remove all but one HTTP implementation from the classpath
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.internal.http.loader.ClasspathSdkHttpServiceProvider.loadService(ClasspathSdkHttpServiceProvider.java:62) ~[sdk-core-2.17.264.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at software.amazon.awssdk.core.internal.http.loader.SdkHttpServiceProviderChain.loadService(SdkHttpServiceProviderChain.java:44) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.internal.http.loader.CachingSdkHttpServiceProvider.loadService(CachingSdkHttpServiceProvider.java:46) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:40) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$7(SdkDefaultClientBuilder.java:343) ~[sdk-core-2.17.264.jar:?]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:343) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:282) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:178) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:27) ~[sts-2.17.264.jar:?]
	at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:22) ~[sts-2.17.264.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:145) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.services.sts.StsClient.create(StsClient.java:79) ~[sts-2.17.264.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.ConnectionConfiguration.attachSigV4(ConnectionConfiguration.java:240) ~[opensearch-2.0.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.ConnectionConfiguration.createClient(ConnectionConfiguration.java:206) ~[opensearch-2.0.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.initialize(OpenSearchSink.java:99) ~[opensearch-2.0.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.<init>(OpenSearchSink.java:90) ~[opensearch-2.0.0-SNAPSHOT.jar:?]
	... 82 more
```

**To Reproduce**

Run Data Prepper against an Amazon OpenSearch Service domain.

**Additional context**

The AWS Java SDK v2 is providing multiple clients by default. They are conflicting with each other.

**Comment by dlvenable** [comment]
There are a few ways to configure the client in use. You can see the various options in this post about configuring one of them. https://aws.amazon.com/blogs/developer/introducing-aws-common-runtime-http-client-in-the-aws-sdk-for-java-2-x/

I'd like to make Apache the default by removing all but the `apache-client`.

**Comment by dlvenable** [comment]
I also was able to reproduce this issue when using S3 as a source with an OpenSearch Docker sink.

```
2022-10-04T14:43:22,644 [main] ERROR org.opensearch.dataprepper.pipeline.Pipeline - Pipeline [log-pipeline] encountered exception while starting the source, skipping execution
software.amazon.awssdk.core.exception.SdkClientException: Multiple HTTP implementations were found on the classpath. To avoid non-deterministic loading implementations, please explicitly provide an HTTP client via the client builders, set the software.amazon.awssdk.http.service.impl system property with the FQCN of the HTTP service to use as the default, or remove all but one HTTP implementation from the classpath
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.internal.http.loader.ClasspathSdkHttpServiceProvider.loadService(ClasspathSdkHttpServiceProvider.java:62) ~[sdk-core-2.17.264.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at software.amazon.awssdk.core.internal.http.loader.SdkHttpServiceProviderChain.loadService(SdkHttpServiceProviderChain.java:44) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.internal.http.loader.CachingSdkHttpServiceProvider.loadService(CachingSdkHttpServiceProvider.java:46) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:40) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$7(SdkDefaultClientBuilder.java:343) ~[sdk-core-2.17.264.jar:?]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:343) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:282) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:178) ~[sdk-core-2.17.264.jar:?]
	at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:27) ~[sts-2.17.264.jar:?]
	at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:22) ~[sts-2.17.264.jar:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:145) ~[sdk-core-2.17.264.jar:?]
	at org.opensearch.dataprepper.plugins.source.configuration.AwsAuthenticationOptions.authenticateAwsConfiguration(AwsAuthenticationOptions.java:45) ~[s3-source-2.0.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.source.S3Service.createS3Client(S3Service.java:65) ~[s3-source-2.0.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.source.S3Service.<init>(S3Service.java:46) ~[s3-source-2.0.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.source.S3Source.start(S3Source.java:50) ~[s3-source-2.0.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.pipeline.Pipeline.execute(Pipeline.java:160) ~[data-prepper-core-2.0.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.DataPrepper.lambda$execute$0(DataPrepper.java:75) ~[data-prepper-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at org.opensearch.dataprepper.DataPrepper.execute(DataPrepper.java:74) ~[data-prepper-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.opensearch.dataprepper.DataPrepperExecute.main(DataPrepperExecute.java:41) ~[data-prepper-main-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
```
