### ISSUE TITLE
[BUG] S3 TestEvent stuck in SQS queue

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1924]
**Describe the bug**

The Data Prepper S3 source fails to process `s3:TestEvent` objects. These remain the SQS queue and are reprocessed over and over again.

**To Reproduce**

Configure the S3 bucket to send notifications to SQS. It will create an SQS record for `s3:TestEvent`.

Create an S3 source pipeline in Data Prepper. Run it.

**Expected behavior**

Data Prepper should recognize the `s3:TestEvent` and remove it from the SQS queue. It should also not add this to the buffer. Ideally it does output the fact it received it since this can be useful for whomever is running Data Prepper to check that the SQS queue reads work.

**Actual Output**

```
2022-10-15T17:09:11,275 [Thread-1] ERROR org.opensearch.dataprepper.plugins.source.SqsWorker - Invalid JSON string in message body of bf803036-5fd3-4857-9db2-d608be440d8d
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Service" (class org.opensearch.dataprepper.plugins.source.S3EventNotification), not marked as ignorable (one known property: "Records"])
 at [Source: (String)"{"Service":"Amazon S3","Event":"s3:TestEvent","Time":"2022-10-15T16:36:25.510Z","Bucket":"***","RequestId":"***","HostId":"***"}"; line: 1, column: 233] (through reference chain: org.opensearch.dataprepper.plugins.source.S3EventNotification["Service"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1650) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:540) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597) ~[jackson-databind-2.13.4.jar:2.13.4]
	at org.opensearch.dataprepper.plugins.source.S3EventNotification.parseJson(S3EventNotification.java:58) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.source.SqsWorker.convertS3EventMessages(SqsWorker.java:137) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at org.opensearch.dataprepper.plugins.source.SqsWorker.getS3MessageEventNotificationRecordMap(SqsWorker.java:132) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.source.SqsWorker.processSqsMessages(SqsWorker.java:99) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.source.SqsWorker.run(SqsWorker.java:76) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Environment (please complete the following information):**

Data Prepper 2.1.0-SNAPSHOT from `main` build.

**Additional context**

Connecting an S3 Event Subscription to SQS will create this test message.

**Comment by asifsmohammed** [comment]
One possible solution is to have the following condition in the following method,
```
private List<S3EventNotification.S3EventNotificationRecord> convertS3EventMessages(final Message message) {
        if (message.body().contains("s3:TestEvent") && message.body().contains("Amazon S3")) {
            deleteSqsMessages(Collections.singletonList(buildDeleteMessageBatchRequestEntry(message)));
        }
```

https://github.com/opensearch-project/data-prepper/blob/a66da8e16ae95bab9b0e86a50af0f7efb6b5b98b/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java#L135-L143

**Comment by dlvenable** [comment]
Here is the body from my SQS queue:

```
{"Service":"Amazon S3","Event":"s3:TestEvent","Time":"2022-10-15T16:36:25.510Z","Bucket":"bucketname","RequestId":"***","HostId":"***"}
```

**Comment by dlvenable** [comment]
I think it would make sense to try to parse the message like we normally do. Then we can add the condition you have as part of the exception handling.

A couple reasons to recommend this:
* I'd prefer that we assume the message is an S3 notification. This way, in the unlikely scenario those strings are in the body somewhere else, we don't let them interfere.
* These messages are only created when setting up an S3 notification. This should happen relatively rarely, so we don't have to waste time checking the message for these strings.

Also, I think it is worthwhile to print that Data Prepper received the TestEvent. It could be useful for debugging. Maybe just an `INFO` line about it.
