### ISSUE TITLE
[BUG] Docker image doesn't honor the ENV variables for pipeline and config files.

### ISSUE THREAD

**Issue by arunx2** [opensearch-project/data-prepper#2008]
**Describe the bug**
The 2.0.1 docker image declares two ENV variables in [image](https://hub.docker.com/layers/opensearchproject/data-prepper/2.0.1/images/sha256-3e3f836ba107dd322687da4972a64b3d52e8760980f2e0b39b8bc2e6e72aa7a8?context=explore) layer 16 and 17
ENV_CONFIG_FILEPATH=/usr/share/data-prepper/config/data-prepper-config.yaml
ENV_PIPELINE_FILEPATH=/usr/share/data-prepper/pipelines/pipelines.yaml

It looks like the engine doesn't consider the values from ENV variable. It works with 1.5.1 image and doesn't with 2.0.1. I'm aware that the folder structure changed. My expectation is either it should work or documented as part of breaking changes.

**To Reproduce**
Here is my k8s manifest which works in 1.5.1 and doesn't with 2.0.1
`apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: data-prepper
  name: data-prepper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-prepper
  template:
    metadata:
      labels:
        k8s-app: tracing
        io.kompose.service: data-prepper
    spec:
      containers:
        - image: opensearchproject/data-prepper:2.0.1
          name: data-prepper
          env:
            - name: ENV_PIPELINE_FILEPATH
              value: /usr/share/data-prepper-config/pipelines.yaml
            - name: ENV_CONFIG_FILEPATH
              value: /usr/share/data-prepper-config/data-prepper-config.yaml
          ports:
            - containerPort: 21890
          volumeMounts:
            - mountPath: /usr/share/data-prepper-config
              name: data-prepper-config
      restartPolicy: Always
      volumes:
        - name: data-prepper-config
          configMap:
            name: otel-configmap
            items:
              - key: data-prepper-pipeline
                path: pipelines.yaml
              - key: data-prepper-config
                path: data-prepper-config.yaml`

**Expected behavior**
It should work as my ENV variables pointing to the right config files. But I get
`Caused by: org.opensearch.dataprepper.parser.ParseException: Pipelines configuration file not found at /usr/share/data-prepper/pipelines
        at org.opensearch.dataprepper.parser.PipelineParser.mergePipelineConfigurationFiles(PipelineParser.java:137)
        at org.opensearch.dataprepper.parser.PipelineParser.parseConfiguration(PipelineParser.java:84)
        at org.opensearch.dataprepper.DataPrepper.<init>(DataPrepper.java:60)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)`

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]
 - Version [e.g. 22] : 2.0.01

**Additional context**

**Comment by dlvenable** [comment]
Thank you for reporting this issue @arunx2 !

It seems that Data Prepper should either:
* Correctly support `ENV_PIPELINE_FILEPATH` and `ENV_PIPELINE_FILEPATH` with the most recent changes in 2.0; or
* Remove these so that users do not set them.
