### ISSUE TITLE
OpenSearch sink config option for data streams

### ISSUE THREAD

**Issue by rospeelman** [opensearch-project/data-prepper#2038]
**Is your feature request related to a problem? Please describe.**
At the Moment Data Prepper can not send data to an OpenSearch data stream

**Describe the solution you'd like**
A configoration option for the OpenSearch sink to support a data stream

**Comment by dlvenable** [comment]
@rospeelman , Thank you for the suggestion! Is the idea here that after Data Prepper initializes the index template, it also performs a request to [create a data stream](https://opensearch.org/docs/latest/opensearch/data-streams/#step-2-create-a-data-stream)?

**Comment by rospeelman** [comment]
at the moment the OpenSearch sink does not support data streams as seen in this issue #2037. An option to enable this would be enough, but the create request would be nice too.

**Comment by asifsmohammed** [comment]
After looking into this, looks like the workaround is to 
1. Create an index template with Data Stream
```
{
  "index_patterns": [
    "my-data-stream",
    "logs-*"
  ],
  "data_stream": {},
  "priority": 100
}
```  
2. Configure the opensearch plugin in Data Prepper to use `index_type: management_disabled` .

```
pipeline:
  ...
  sink:
    opensearch:
      hosts: ["https://localhost:9200"]
      index_type: management_disabled
      index: "logs-time-series"
```

I believe this should work, as we don't need to explicitly create Data Stream if it's part of Index template and start ingesting.
https://opensearch.org/docs/latest/im-plugin/data-streams/#step-2-create-a-data-stream

**Comment by sharraj** [comment]
[asifsmohammed](https://github.com/asifsmohammed) Also comment what needs to be done to add this feature natively in Data Prepper. Creating index from pipelines is a useful functionality.

**Comment by cameronattard** [comment]
The issue here is not related to creating a data stream - it is the action performed when sending requests to OpenSearch. To solve this, Data Prepper should implement an `action` attribute on the OpenSearch sink, similar to what LogStash has done here - https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-action

**Comment by cameronattard** [comment]
`create` doesn't seem to work for me on the latest version:

```
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        insecure: true
        username: admin
        password: admin
        index: kubernetes_logs
        action: create

```

```
2023-07-22T02:00:35,667 [log-pipeline-sink-worker-2-thread-1] ERROR org.opensearch.dataprepper.pipeline.common.PipelineThreadPoolExecutor - Pipeline [log-pipeline] process worker encountered a fatal exception, cannot proceed further
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot get 'Index' variant: current variant is 'Create'.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at org.opensearch.dataprepper.pipeline.common.PipelineThreadPoolExecutor.afterExecute(PipelineThreadPoolExecutor.java:70) [data-prepper-core-2.3.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by cameronattard** [comment]
I suspect the above may be resolved once this is released: https://github.com/opensearch-project/data-prepper/pull/3041

**Comment by dlvenable** [comment]
I'm closing this in favor of #6828.
