### ISSUE TITLE
[BUG] Invalid Opentelemetry Data can cause ingestion to be stopped

### ISSUE THREAD

**Issue by KarstenSchnitter** [opensearch-project/data-prepper#2089]
Using DataPrepper to ingest metrics into OpenSearch it is possible to crash the metrics ingestion with invalid data. If data points without a value are sent, the null check in the OtelMetricsRawProcessor throws a NullPointerException. This crashes the current ingestion thread. Once all threads crash, no more data ingestion is possible. DataPrepper does not restart failed threads nor does it crash itself. Additional monitoring of the buffers or logs is required to detect this disfunctional state. Restarting DataPrepper resolves the issue until the next invalid data point is ingested. During restarts all data in the buffers is lost.

**To Reproduce**
We encountered the issue using the OpenTelemetry Collector to scrape Istio metrics from its Prometheus endpoint. Since the issue only happens occasionally and could not be forced, we provide an alternative approach, that generates the invalid metrics directly. Nevertheless, keep in mind, that the issue happened in a productive setup.

1. Run DataPrepper with a default metrics pipeline, e.g.:
```
    metrics-pipeline:
      source:
        otel_metrics_source:
          ssl: false
      processor:
        - otel_metrics_raw_processor:
```
2. Store the following OTEL metric as JSON in a file `metric.json`. Note, that there is no "value" field in the data point.
```
{
    "resourceMetrics": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "service.name",
                        "value": {
                            "stringValue": "basic-metric-service"
                        }
                    }
                ],
                "droppedAttributesCount": 0
            },
            "scopeMetrics": [
                {
                    "metrics": [
                        {
                            "description": "Example of a Counter",
                            "name": "requests",
                            "gauge": {
                                "dataPoints": [
                                    {
                                        "attributes": [],
                                        "startTimeUnixNano": 1660736598000000000,
                                        "timeUnixNano": 1660736598000001000
                                    }
                                ]
                            },
                            "unit": "1"
                        }
                    ],
                    "scope": {
                        "name": "example-exporter-collector",
                        "version": ""
                    }
                }
            ]
        }
    ]
}
```
3. Prepare a otel-collector docker image, e.g. `docker pull otel/opentelemetry-collector:0.67.0` and point it to the DataPrepper instance using the following configuration:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "*"

processors:
  batch:
    send_batch_size: 50
    timeout: 1s

exporters:
  logging:
    logLevel: debug
  otlp/metrics:
    endpoint: "<DataPrepper Endpoint>"
    tls:
      insecure_skip_verify: true
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/metrics]
```
4. Run the Docker image with:
```
docker run -v "${PWD}/otelcol-config-sample.yaml":/otelcol-config-sample.yaml -p 4318:4318 otel/opentelemetry-collector:0.67.0 --config otelcol-config-sample.yaml
```
5. Send the invalid metric to the otel-collector:
```
curl -X POST -H "Content-Type: application/json" -d @metric-request-gauge.json http://localhost:4318/v1/metrics
``` 

The OpenTelemetry Collector should send the invalid metric to DataPrepper causing the NPE (stacktrace from DataPrepper 1.5):
```
2022-11-23T16:23:08,402 [metrics-pipeline-processor-worker-7-thread-1] ERROR com.amazon.dataprepper.pipeline.ProcessWorker - Encountered exception during pipeline metrics-pipeline processing
java.lang.NullPointerException: value cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.model.metric.ParameterValidator.lambda$validate$2(ParameterValidator.java:33) ~[data-prepper.jar:1.5.0]
	at java.util.Collections$SingletonList.forEach(Collections.java:4933) ~[?:?]
	at com.amazon.dataprepper.model.metric.ParameterValidator.validate(ParameterValidator.java:31) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.model.metric.JacksonGauge$Builder.build(JacksonGauge.java:80) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.plugins.processor.otelmetrics.OTelMetricsRawProcessor.lambda$mapGauge$0(OTelMetricsRawProcessor.java:89) ~[data-prepper.jar:1.5.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.amazon.dataprepper.plugins.processor.otelmetrics.OTelMetricsRawProcessor.mapGauge(OTelMetricsRawProcessor.java:91) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.plugins.processor.otelmetrics.OTelMetricsRawProcessor.doExecute(OTelMetricsRawProcessor.java:54) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.model.processor.AbstractProcessor.lambda$execute$0(AbstractProcessor.java:55) ~[data-prepper.jar:1.5.0]
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:65) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.model.processor.AbstractProcessor.execute(AbstractProcessor.java:55) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:62) ~[data-prepper.jar:1.5.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
```

**Expected behavior**
DataPrepper should not lose a worker thread to faulty input data. The metric should be dropped increasing an appropriate counter in the metrics. Optionally a log entry can be issued at DEBUG or INFO level.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]
 - DataPrepper versions 1.5 and 2.0 were tested. Both with local binaries and the provided Docker images.

**Additional context**
The issue is cause by declaring the value field as "REQUIRED_NON_NULL_VALUES" in the JacksonGauge: https://github.com/opensearch-project/data-prepper/blob/01228357aa9f5c6f8099887b3c90d15e892c769c/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonGauge.java#L25-L29.
Since the validation exceptions are not called and handled, the worker thread crashes. It would be nice, if a different behaviour on validation errors would be implemented as indicated in expected behaviour.

**Comment by kkondaka** [comment]
Taking a look

**Comment by dlvenable** [comment]
Thanks for reporting these issues and the detailed steps!
I created #2185 to track the Trace ingestion issue. The problem here is a little more complicated than with metrics and might require a different solution.

**Comment by dlvenable** [comment]
The solution that @kkondaka has in #2176 for metrics is to drop the metrics data in the `otel_metrics_raw_processor` when it does not conform to our expectations. Additionally it will include a metric to track this. I believe with some modifications this will work for the metrics issue.
