### ISSUE TITLE
[BUG] Null pointer exception in Data-prepper while doing peer forwarding

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2123]
**Describe the bug**
Data-prepper crashes with null pointer exception when remote peer forwarder sees an event without identification keys.

stack trace is -
ava.lang.NullPointerException: Cannot invoke "Object.toString()" because "identificationKeyValue" is null
        at org.opensearch.dataprepper.peerforwarder.RemotePeerForwarder.groupRecordsBasedOnIdentificationKeys(RemotePeerForwarder.java:156) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.peerforwarder.RemotePeerForwarder.forwardRecords(RemotePeerForwarder.java:86) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.peerforwarder.PeerForwardingProcessorDecorator.execute(PeerForwardingProcessorDecorator.java:81) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.pipeline.ProcessWorker.doRun(ProcessWorker.java:95) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:45) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**To Reproduce**
1. Start data prepper with at least two nodes with peer forwarder configuration
2. Use pipeline configuration with aggregate processor and identification keys
3. Send events which do not have the identification keys in them
4. See null pointer exception

**Expected behavior**
Expected behavior is to ignore the events that do not have the identification keys

**Comment by dlvenable** [comment]
@kkondaka , Do you have a stack trace for this NPE?
