### ISSUE TITLE
[BUG] Performance with one data-prepper instance is better than with two

### ISSUE THREAD

**Issue by JannikBrand** [opensearch-project/data-prepper#2147]
**Describe the bug**
When sending load to data-prepper (2 instances) we can see a huge performance difference compared to if we only would have 1 instance of data-prepper with the same configuration (but without the Core Peer Forwarder).

**To Reproduce**
1. Run data-prepper with the following configuration:
Note: We are running data-prepper within Kubernetes and using a headless service for the peer forwarder. Like documented [here](https://github.com/opensearch-project/data-prepper/blob/main/examples/dev/k8s/data-prepper.yaml) in the examples/dev/k8s folder.
```
data-prepper-config.yaml:
     ssl: false
     peer_forwarder:
       ssl: false
       discovery_mode: "dns"
       domain_name: "data-prepper-headless"
       buffer_size: 512 
       batch_size: 48
```
```
entry-pipeline:
  workers: 8
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 8
  processor:
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  workers: 8
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 64
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ <opensearch endpoint> ]
        insecure: true
        username: <user>
        password: <pwd>
        index_type: trace-analytics-raw
service-map-pipeline:
  workers: 8
  delay: "100"
  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 8
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: [<opensearch endpoint>]
        insecure: true
        username: <user>
        password: <pwd>
        index_type: trace-analytics-service-map
```
2. Prepare an otel-collector docker image, e.g. docker pull otel/opentelemetry-collector:0.67.0 and point it to the DataPrepper instance using the following configuration:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "*"

processors:
  batch:
    send_batch_size: 50
    timeout: 1s

exporters:
  logging:
    logLevel: debug
  otlp/traces:
    endpoint: "<DataPrepper Endpoint>"
    tls:
      insecure_skip_verify: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/traces]
```
3. Run the otel-collector:
`docker run -v "${PWD}/otelcol-config-sample.yaml":/otelcol-config-sample.yaml -p 4318:4318 otel/opentelemetry-collector:0.67.0 --config otelcol-config-sample.yaml`

4. Get [tracegen](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/tracegen) as simple load generation tool:
`go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/tracegen@latest
`
5. Run tracegen to send trace spans to the otel-collector (here 500 requests per second, each request having two spans). The otel-collector will export those to data-prepper.
`tracegen -otlp-http -otlp-endpoint localhost:4318 -otlp-insecure -duration 300s -rate 500
`

After a few seconds I can see logs like the following:
```
2023-01-13T16:40:04,634 [pool-7-thread-6] ERROR org.opensearch.dataprepper.plugins.source.oteltrace.OTelTraceGrpcService - Failed to write the request content [
<here are all the spans, too many to paste them>
] due to:
java.util.concurrent.TimeoutException: Pipeline [entry-pipeline] - Buffer does not have enough capacity left for the size of records: 512, timed out waiting for slots.
	at org.opensearch.dataprepper.plugins.buffer.blockingbuffer.BlockingBuffer.doWriteAll(BlockingBuffer.java:123) ~[blocking-buffer-2.0.1.jar:?]
	at org.opensearch.dataprepper.model.buffer.AbstractBuffer.writeAll(AbstractBuffer.java:97) ~[data-prepper-api-2.0.1.jar:?]
	at org.opensearch.dataprepper.plugins.MultiBufferDecorator.writeAll(MultiBufferDecorator.java:39) ~[data-prepper-core-2.0.1.jar:?]
	at org.opensearch.dataprepper.plugins.source.oteltrace.OTelTraceGrpcService.processRequest(OTelTraceGrpcService.java:106) ~[otel-trace-source-2.0.1.jar:?]
	at org.opensearch.dataprepper.plugins.source.oteltrace.OTelTraceGrpcService.lambda$export$0(OTelTraceGrpcService.java:78) ~[otel-trace-source-2.0.1.jar:?]
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:89) ~[micrometer-core-1.9.4.jar:1.9.4]
	at org.opensearch.dataprepper.plugins.source.oteltrace.OTelTraceGrpcService.export(OTelTraceGrpcService.java:78) ~[otel-trace-source-2.0.1.jar:?]
	at io.opentelemetry.proto.collector.trace.v1.TraceServiceGrpc$MethodHandlers.invoke(TraceServiceGrpc.java:246) ~[opentelemetry-proto-1.7.1-alpha.jar:1.7.1]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.49.0.jar:1.49.0]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.invokeOnMessage(AbstractServerCall.java:374) ~[armeria-grpc-1.19.0.jar:?]
	at com.linecorp.armeria.server.grpc.AbstractServerCall.lambda$onRequestMessage$2(AbstractServerCall.java:338) ~[armeria-grpc-1.19.0.jar:?]
	at com.linecorp.armeria.internal.shaded.guava.util.concurrent.SequentialExecutor$1.run(SequentialExecutor.java:123) ~[armeria-1.19.0.jar:?]
	at com.linecorp.armeria.internal.shaded.guava.util.concurrent.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:235) ~[armeria-1.19.0.jar:?]
	at com.linecorp.armeria.internal.shaded.guava.util.concurrent.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:180) ~[armeria-1.19.0.jar:?]
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:566) ~[armeria-1.19.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
**Expected behavior**
I expect that increasing the instances of data-prepper will improve the performance and not make it worse.

**Screenshots**
![dpissue](https://user-images.githubusercontent.com/121185951/212376480-82a1b30d-feee-45a5-8ca6-5a060f9bd7d3.png)

In this screenshot we can see how many spans got ingested into OpenSearch. On the left we have the load generation for 2 data-prepper instances and on the right for 1 instance. On the right we can see that no traces are lost and on the left only a few will get through.

**Environment (please complete the following information):**
- Tested with data-prepper 2.0.1. Having the same configuration, for 1.5.0 it could support the same load rate without problems.

**Additional context**

The pipeline definition uses values for the buffer and batch sizes and workers like documented [here](https://github.com/opensearch-project/data-prepper/blob/7901643baccc5e75675eb578362e2ea587a5ca9a/docs/trace_analytics.md). We noticed that the default sizes for buffer and batch size (512 & 8) changed with data-prepper version 2.0 to 12800 & 200. This also helps to deal with this issue and data-prepper can handle much more load this way. Also, by increasing the buffer and batch size for the peer forwarder we can improve the performance so that it will be close to look like the result when we just are using 1 data-prepper instance.
However, it still seems to be better when just having one instance compared to having two. The "outdated" values for the buffer and batch size are used here to show that we get a worse performance for two data-prepper instances.

**Comment by JannikBrand** [comment]
We also often see the following warning with the exact same setup:
```
2023-01-13T16:09:54,629 [raw-pipeline-sink-worker-6-thread-1] WARN  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Document [org.opensearch.client.opensearch.core.bulk.BulkOperation@1c33b63b] has failure.
java.lang.NullPointerException: Cannot invoke "org.opensearch.client.json.JsonpDeserializer.acceptedEvents()" because the return value of "org.opensearch.client.json.DelegatingDeserializer.unwrap()" is null
	at org.opensearch.client.json.DelegatingDeserializer.acceptedEvents(DelegatingDeserializer.java:50) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.acceptedEvents(JsonpDeserializerBase.java:318) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.json.JsonpUtils.ensureAccepts(JsonpUtils.java:80) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:85) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:189) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:150) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:92) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:320) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:286) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:143) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.client.opensearch.OpenSearchClient.bulk(OpenSearchClient.java:211) ~[opensearch-java-1.0.0.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.lambda$initialize$1(OpenSearchSink.java:112) ~[opensearch-2.0.1.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.BulkRetryStrategy.handleRetry(BulkRetryStrategy.java:97) ~[opensearch-2.0.1.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.BulkRetryStrategy.execute(BulkRetryStrategy.java:71) ~[opensearch-2.0.1.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.lambda$flushBatch$2(OpenSearchSink.java:206) ~[opensearch-2.0.1.jar:?]
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:89) ~[micrometer-core-1.9.4.jar:1.9.4]
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.flushBatch(OpenSearchSink.java:203) ~[opensearch-2.0.1.jar:?]
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.doOutput(OpenSearchSink.java:177) ~[opensearch-2.0.1.jar:?]
	at org.opensearch.dataprepper.model.sink.AbstractSink.lambda$output$0(AbstractSink.java:38) ~[data-prepper-api-2.0.1.jar:?]
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:89) ~[micrometer-core-1.9.4.jar:1.9.4]
	at org.opensearch.dataprepper.model.sink.AbstractSink.output(AbstractSink.java:38) ~[data-prepper-api-2.0.1.jar:?]
	at org.opensearch.dataprepper.pipeline.Pipeline.lambda$publishToSinks$3(Pipeline.java:247) ~[data-prepper-core-2.0.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
I try if I can simplify the setup only for the purpose of reproducing this warning log. Then I can also create a separate Issue because it could be unrelated to this one.

**Comment by dlvenable** [comment]
@JannikBrand ,

I see that your batch size is set to 8 (`batch_size: 8`) in the pipeline configuration. In Data Prepper 2.0, the `otel_trace_source` puts each span into the buffer as its own record. Previously it would put the OTel trace request object. This object could have 50 or so spans.

This can impact performance both for Data Prepper on its own and with peer forwarding.

The peer forwarder does not batch requests between peers. So with a batch size of 8, if 4 need to go to another peer, each HTTP request will hold only 4 events (spans). This could result in a lot of requests between peers.

I recommend that at a minimum, you multiply your batch size by 50 since previously 50 spans/event were normal. This is somewhat conservative. I actually recommend that you try increasing it even more, but you'd need to tune this. Even if you set the batch size to 400 (8 * 50), you will likely send 200 events per HTTP request between peers. That could make a significant difference.

Similarly, I recommend increasing the buffer size by at least a scale of 50. So 25,600. We have found that increasing the buffer size can help much with throughput. I recommend starting with 25,600 and then trying to tune it higher.

Please also consider increasing the `batch_size` in the peer forwarder configuration to 400.

Please let me know if any of these changes help.

**Comment by engechas** [comment]
I am able to repro this. I tried a few different configurations to see what the effect would be. All of these runs used a tracegen rate of 500 against a 2 node Data Prepper pipeline. 

![image](https://user-images.githubusercontent.com/62891993/213271239-da2bb062-392c-42e5-b633-d740f0dbfb59.png)

**Marker 1**
Setup: buffer configurations from the issue description
Results: Data Prepper chokes immediately as the entry-pipeline buffer is full

**Marker 2**
Setup: pipeline buffers set to 25600 size and 400 batch, no change to peer forwarder buffer configuration
Results: Data Prepper chokes very quickly as the peer forwarder buffer is full and rejecting requests

**Marker 3**
Setup: pipeline buffers set to 25600 size and 4000 batch, no change to peer forwarder buffer configuration
Results: Data Prepper still chokes, but the increased batch size allows it hang on a little longer

**Marker 4**
Setup: pipeline buffers set to 25600 size and 400 batch, peer forwarder buffer set to 25600 size and 400 batch
Results: Data Prepper is able to handle the load with no rejections

**Marker 5**
Setup: pipeline buffers set to 25600 size and 400 batch, no change to peer forwarder buffer configuration, peer forwarder request timeout set to 500ms (default is 10000ms)
Results: Data Prepper hangs on a bit longer but eventually chokes and starts rejecting requests

The primary culprit here is the buffer configurations, but there is a secondary mechanism subtly impacting performance. The pipeline buffers saturating and causing source rejections makes sense, and it follows that this would have a direct impact on performance. The performance degradation going from 1 node to 2 is a bit less transparent. Once the peer forwarder buffer saturates and begins rejecting requests, the data is processed on the local node. On the surface, this doesn't seem like it should have a significant impact on throughput as long as the local node is not saturated.

The PeerForwarderClient makes a blocking call to forward data as it waits for the response from the peer server [here](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/client/PeerForwarderClient.java#L123), which is dependent on the `request_timeout` parameter of the peer forwarder configuration. This call prevents a `ProcessWorker` from making progress until it completes, which chokes Data Prepper's throughput.

I think there's a few action items here:
Low hanging fruit: increase default buffer and batch size for peer forwarder
Low hanging fruit: decrease default request timeout for peer forwarder
High hanging fruit: find a way to avoid the blocking during the call to the peer forwarder server so that the ProcessWorkers can continue working in the background

**Comment by engechas** [comment]
The above explains the performance degradation from 1->2 nodes. I am now looking into whether 2 nodes provides a roughly linear performance increase over 1 node

**Comment by JannikBrand** [comment]
Thanks for the detailed explanations, @dlvenable and @engechas !
Regarding the values for the `buffer_size` and `batch_size` I was also already testing larger values than 512 and 8. For the setup from the issue description I used those values since they more clearly produced this result, that one instance of Data Prepper is performing better than two instances. However, I was not using such large numbers which @dlvenable has recommended here. I rather oriented myself on the default values specified [here](https://github.com/opensearch-project/data-prepper/blob/29a4a9750c5448cc7ecf27246f6565fb483fa724/data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java#L46). Trying your recommendations, the performance is much better, the problems seem to be gone! One remark: When comparing version 1.5.x with 2.0.x I would need to assign more memory than before to support the same amount of load.

Some questions regarding your recommendations:

- On various places I can still see that there are the old default values (512 & 8) for `buffer_size` and `batch_size` documented ([here](https://github.com/opensearch-project/data-prepper/tree/29a4a9750c5448cc7ecf27246f6565fb483fa724/data-prepper-plugins/blocking-buffer), [here](https://github.com/opensearch-project/data-prepper/blob/7901643baccc5e75675eb578362e2ea587a5ca9a/docs/trace_analytics.md), [here](https://opensearch.org/docs/latest/data-prepper/data-prepper-reference/)). It would makes sense to update them to the [new](https://github.com/opensearch-project/data-prepper/blob/29a4a9750c5448cc7ecf27246f6565fb483fa724/data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java#L46) default values. If you want me to create a PR, I can do so.
- There are three pipelines. Now, @engechas tested setting the blocking buffer to `buffer_size`: 25600, `batch_size`: 400 for all of them. In this [documentation](https://github.com/opensearch-project/data-prepper/blob/7901643baccc5e75675eb578362e2ea587a5ca9a/docs/trace_analytics.md) it is mentioned that it makes sense to increase the `batch_size` for the `raw-pipeline` even more (by a factor of 8). Would it makes sense also for your recommendations to set the `batch_size` of the `raw-pipeline` to sth. like 400*8 = 3200?
- The ratio between `buffer_size` and `batch_size` is 25600/400 (= 512/8) = 64. For the peer forwarder it [is](https://github.com/opensearch-project/data-prepper/blob/1557cae5fe1e24a5cdbfdf81e04d7d8db516b33f/data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java#L54) 512/48. During your experiment you changed the ratio to 25600/400. Would it makes sense to keep the default ratio, e.g. 25600/2400, or does this not matter to much?
---

>The above explains the performance degradation from 1->2 nodes. I am now looking into whether 2 nodes provides a roughly linear performance increase over 1 node

 Cool, I am curious to see, how scaling out would improve the performance situation.

**Comment by dlvenable** [comment]
> Trying your recommendations, the performance is much better, the problems seem to be gone! 

That's great to hear! And thank you for trying out the change and reporting back!

> One remark: When comparing version 1.5.x with 2.0.x I would need to assign more memory than before to support the same amount of load.

I'd definitely like us to dive into this one. What do you mean when you say assign more memory? Are you having to increase the maximum Java heap size? Or do you mean something different? 

> On various places I can still see that there are the old default values (512 & 8) for buffer_size and batch_size documented ([here](https://github.com/opensearch-project/data-prepper/tree/29a4a9750c5448cc7ecf27246f6565fb483fa724/data-prepper-plugins/blocking-buffer), [here](https://github.com/opensearch-project/data-prepper/blob/7901643baccc5e75675eb578362e2ea587a5ca9a/docs/trace_analytics.md), [here](https://opensearch.org/docs/latest/data-prepper/data-prepper-reference/)). It would makes sense to update them to the [new](https://github.com/opensearch-project/data-prepper/blob/29a4a9750c5448cc7ecf27246f6565fb483fa724/data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java#L46) default values. If you want me to create a PR, I can do so.

I would very much appreciate a PR for these! Do note that the opensearch.org/docs page has changed quite a bit on `main` from what is currently deployed. [This is](https://github.com/opensearch-project/documentation-website/blob/main/_data-prepper/configuration/buffers/bounded-blocking.md) the new source file for a configuration reference for `bounded_buffer`. If you create a PR in that repo, please tag me.

> There are three pipelines. Now, @engechas tested setting the blocking buffer to buffer_size: 25600, batch_size: 400 for all of them. In this [documentation](https://github.com/opensearch-project/data-prepper/blob/7901643baccc5e75675eb578362e2ea587a5ca9a/docs/trace_analytics.md) it is mentioned that it makes sense to increase the batch_size for the raw-pipeline even more (by a factor of 8). Would it makes sense also for your recommendations to set the batch_size of the raw-pipeline to sth. like 400*8 = 3200?

Yes, I believe so. The same reasoning as in the comment applies here. The guidance suggested being able to support processing 3200 spans in a batch. With the new event model, that is exactly what you will get here. `batch_size = 3200` means process 3200 spans.

> The ratio between buffer_size and batch_size [is](https://github.com/opensearch-project/data-prepper/blob/1557cae5fe1e24a5cdbfdf81e04d7d8db516b33f/data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/PeerForwarderConfiguration.java#L54) 25600/400 (= 512/8) = 64. For the peer forwarder it is 512/48. During your experiment you changed the ratio to 25600/400. Would it makes sense to keep the default ratio, e.g. 25600/2400, or does this not matter to much?

At this moment in time, I don't think you need to worry much about the ratio. We are still doing some tuning on our end and will hopefully be able to provide you some additional guidance if this ratio ends up making a difference.

**Comment by MrSparc** [comment]
I don't want to generate noise by posting this comment in this issue, but I was looking for open performance issues to see if someone is experiencing a similar issue.
I did a checkout from main branch and built a docker image as described in documentation so I can test the new `otel-logs-source` plugin. 
When I replace the use of the official image with this local one in docker-compose and start the container the CPU usage is almost 100% (the laptop's fans spin at full). 
If I go back to using the official data-prepper image, this doesn't happen. 
Will it be something from my local build or a performance regression introduced since the last release. 
 Has anyone experienced an increase in intensive cpu usage with the current code running in a docker?

**Comment by JannikBrand** [comment]
>I'd definitely like us to dive into this one. What do you mean when you say assign more memory? Are you having to increase the maximum Java heap size? Or do you mean something different?

I increased the `resources.requests.memory` and the `resources.limits.memory` value for the K8s data-prepper pods by a factor of two to see if in could handle more load, what it did. Meaning giving the container more memory resources. Otherwise they would be OOM killed in my case. However, the configuration of the heap size stayed the same

>I would very much appreciate a PR for these! Do note that the opensearch.org/docs page has changed quite a bit on main from what is currently deployed. [This is](https://github.com/opensearch-project/documentation-website/blob/main/_data-prepper/configuration/buffers/bounded-blocking.md) the new source file for a configuration reference for bounded_buffer. If you create a PR in that repo, please tag me.

I created both PRs:

- https://github.com/opensearch-project/data-prepper/pull/2233
- https://github.com/opensearch-project/documentation-website/pull/2574

>Yes, I believe so. The same reasoning as in the comment applies here. The guidance suggested being able to support processing 3200 spans in a batch. With the new event model, that is exactly what you will get here. batch_size = 3200 means process 3200 spans.

Thanks again for the feedback!

**Comment by dlvenable** [comment]
@JannikBrand , Thank you for the update. Regarding OOM, we added a JVM-heap based circuit breaker which can help to avoid ingesting too much data. You can read about it in #2150 and it is scheduled for 2.1.

Regarding the peer-forwarding performance, we have found that Data Prepper is serializing data across the wire using YAML. This is a slower serialization. In a quick experiment we found that simply serializing via JSON reduced the server processing latency down by around 60%. I am going to create an issue to update this to using either JSON or Java serialization.

Graph using YAML:

<img width="883" alt="using-yaml" src="https://user-images.githubusercontent.com/293424/216778560-288ecaaf-9ec9-4724-be53-15df10514f3b.png">

Graph using JSON:

<img width="1083" alt="using-json" src="https://user-images.githubusercontent.com/293424/216778563-8a7cf6f5-7a66-4e9f-adb4-66303e12a749.png">

**Comment by MrSparc** [comment]
> I don't want to generate noise by posting this comment in this issue, but I was looking for open performance issues to see if someone is experiencing a similar issue. I did a checkout from main branch and built a docker image as described in documentation so I can test the new `otel-logs-source` plugin. When I replace the use of the official image with this local one in docker-compose and start the container the CPU usage is almost 100% (the laptop's fans spin at full). If I go back to using the official data-prepper image, this doesn't happen. Will it be something from my local build or a performance regression introduced since the last release. The logs of the instance do not show anything abnormal and OTLP gRPC traces / logs are ingested to opensearch right. Even commenting the new plugin the increased cpu usage is the same, so is not `otel-logs-source` related issue. Has anyone experienced an increase in intensive cpu usage with the current code running in a docker?

I have created a corresponding bug issue in the repo: https://github.com/opensearch-project/data-prepper/issues/2244 with more info and including screenshots of profiling DP 2.1.0 application in Docker container
