### ISSUE TITLE
[BUG] High Level Tracking of Flaky Data Prepper Tests

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#3481]
**Describe the bug**
Running the data-prepper build and github actions frequently has failing flaky tests, and often requires retrying the tests multiple times before it succeeds. This issue is meant to allow easy tracking of these flaky tests, by adding an item to the checklist when a flaky test is seen.

### Flaky tests
- [ ]  ```> Task :data-prepper-core:integrationTest PipelinesWithAcksIT > simple_pipeline_with_multiple_records() FAILED
    java.lang.NullPointerException at PipelinesWithAcksIT.java:85```

**Comment by dlvenable** [comment]
```
> Task :data-prepper-core:integrationTest

Router_ThreeRoutesIT > sending_alpha_and_beta_events_sends_to_sinks_that_take_both(String) > [3] ConditionalRoutingIT_alpha_beta_gamma FAILED
    java.lang.AssertionError at Router_ThreeRoutesIT.java:89

Router_ThreeRoutesIT > sending_alpha_and_beta_events_sends_to_both_sinks() FAILED
    java.lang.AssertionError at Router_ThreeRoutesIT.java:112
```

**Comment by dlvenable** [comment]
```
AwsCloudMapPeerListProviderTest > WithSeveralFailedAttempts > listener_gets_list_after_several_failed_attempts() FAILED
    java.lang.AssertionError at AwsCloudMapPeerListProviderTest.java:345
```

**Comment by dlvenable** [comment]
```
PipelinesWithAcksIT > two_pipelines_with_multiple_records() FAILED
    java.lang.NullPointerException at PipelinesWithAcksIT.java:105

```

**Comment by dlvenable** [comment]
```
OTelTraceRawProcessorTest > traceGroupCacheMaxSize_provides_an_upper_bound(long, int) > [1] 1, 4 FAILED
    java.lang.AssertionError at OTelTraceRawProcessorTest.java:270
```

**Comment by dlvenable** [comment]
```
OTelTraceRawProcessorTest > testExportRequestFlushByMixedMultiThread() FAILED
    org.opentest4j.AssertionFailedError at OTelTraceRawProcessorTest.java:193
```

**Comment by dlvenable** [comment]
I saw this error again in a recent build:

```
Router_ThreeRoutesIT > sending_alpha_and_beta_events_sends_to_sinks_that_take_both(String) > [1] ConditionalRoutingIT_all FAILED
    java.lang.AssertionError at Router_ThreeRoutesIT.java:89

Router_ThreeRoutesIT > sending_alpha_and_beta_events_sends_to_sinks_that_take_both(String) > [3] ConditionalRoutingIT_alpha_beta_gamma FAILED
    java.lang.AssertionError at Router_ThreeRoutesIT.java:89
```

**Comment by dlvenable** [comment]
I'm seeing lots of failures in the `kafka-plugins` project in the Java 21 build.

```

> Task :data-prepper-plugins:kafka-plugins:test

KafkaBufferTest > test_kafkaBuffer_producerThrows() FAILED
    java.lang.IllegalAccessError at KafkaBufferTest.java:155

KafkaBufferTest > test_kafkaBuffer_isEmpty_BufferNotEmpty() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > testShutdown_Successful() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > test_kafkaBuffer_isEmpty_TopicNotEmpty() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > test_kafkaBuffer_getDrainTimeout() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > test_kafkaBuffer_doCheckpoint() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > isWrittenOffHeapOnly_returns_true() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > test_kafkaBuffer_isEmpty_True() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > test_kafkaBuffer_basicFunctionality() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > test_kafkaBuffer_postProcess() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > test_kafkaBuffer_doWriteAll() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > testShutdown_Timeout() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > testShutdown_InterruptedException() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KafkaBufferTest > test_kafkaBuffer_isEmpty_MultipleTopics_AllNotEmpty() FAILED
    java.lang.NullPointerException at KafkaBufferTest.java:155

KeyFactoryTest > getKeySupplier_returns_using_first_InnerKeyFactory_that_supports_the_TopicConfig() FAILED
    java.lang.NullPointerException at KeyFactoryTest.java:54

```

```

> Task :data-prepper-plugins:kafka-plugins:test

EncryptionContextTest > fromEncryptionKey_includes_correct_Key() FAILED
    java.lang.AssertionError at EncryptionContextTest.java:55

EncryptionContextTest > encryption_and_decryption_are_symmetric() FAILED
    java.lang.NullPointerException at EncryptionContextTest.java:36

MessageFormatSerializationFactoryTest > getSerializer_returns_expected_deserializer(MessageFormat, Class) > [1] BYTES, class org.apache.kafka.common.serialization.ByteArraySerializer FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:72

MessageFormatSerializationFactoryTest > getSerializer_returns_expected_deserializer(MessageFormat, Class) > [2] PLAINTEXT, class org.apache.kafka.common.serialization.StringSerializer FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:72

MessageFormatSerializationFactoryTest > getSerializer_returns_expected_deserializer(MessageFormat, Class) > [3] JSON, class org.apache.kafka.connect.json.JsonSerializer FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:72

MessageFormatSerializationFactoryTest > getSerializer_returns_expected_deserializer(MessageFormat, Class) > [4] AVRO, class io.confluent.kafka.serializers.KafkaAvroSerializer FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:72

MessageFormatSerializationFactoryTest > getDeserializer_returns_same_instance_for_multiple_calls(MessageFormat) > [1] PLAINTEXT FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:59

MessageFormatSerializationFactoryTest > getDeserializer_returns_same_instance_for_multiple_calls(MessageFormat) > [2] JSON FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:59

MessageFormatSerializationFactoryTest > getDeserializer_returns_same_instance_for_multiple_calls(MessageFormat) > [3] AVRO FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:59

MessageFormatSerializationFactoryTest > getDeserializer_returns_same_instance_for_multiple_calls(MessageFormat) > [4] BYTES FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:59

MessageFormatSerializationFactoryTest > getSerializer_returns_same_instance_for_multiple_calls(MessageFormat) > [1] PLAINTEXT FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:87

MessageFormatSerializationFactoryTest > getSerializer_returns_same_instance_for_multiple_calls(MessageFormat) > [2] JSON FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:87

MessageFormatSerializationFactoryTest > getSerializer_returns_same_instance_for_multiple_calls(MessageFormat) > [3] AVRO FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:87

MessageFormatSerializationFactoryTest > getSerializer_returns_same_instance_for_multiple_calls(MessageFormat) > [4] BYTES FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:87

MessageFormatSerializationFactoryTest > getDeserializer_returns_deserializer_instance(MessageFormat) > [1] PLAINTEXT FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:51

MessageFormatSerializationFactoryTest > getDeserializer_returns_deserializer_instance(MessageFormat) > [2] JSON FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:51

MessageFormatSerializationFactoryTest > getDeserializer_returns_deserializer_instance(MessageFormat) > [3] AVRO FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:51

MessageFormatSerializationFactoryTest > getDeserializer_returns_deserializer_instance(MessageFormat) > [4] BYTES FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:51

MessageFormatSerializationFactoryTest > getDeserializer_returns_expected_deserializer(MessageFormat, Class) > [1] BYTES, class org.apache.kafka.common.serialization.ByteArrayDeserializer FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:44

MessageFormatSerializationFactoryTest > getDeserializer_returns_expected_deserializer(MessageFormat, Class) > [2] PLAINTEXT, class org.apache.kafka.common.serialization.StringDeserializer FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:44

MessageFormatSerializationFactoryTest > getDeserializer_returns_expected_deserializer(MessageFormat, Class) > [3] JSON, class org.apache.kafka.connect.json.JsonDeserializer FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:44

MessageFormatSerializationFactoryTest > getDeserializer_returns_expected_deserializer(MessageFormat, Class) > [4] AVRO, class io.confluent.kafka.serializers.KafkaAvroDeserializer FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:44

MessageFormatSerializationFactoryTest > getSerializer_returns_deserializer_instance(MessageFormat) > [1] PLAINTEXT FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:79

MessageFormatSerializationFactoryTest > getSerializer_returns_deserializer_instance(MessageFormat) > [2] JSON FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:79

MessageFormatSerializationFactoryTest > getSerializer_returns_deserializer_instance(MessageFormat) > [3] AVRO FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:79

MessageFormatSerializationFactoryTest > getSerializer_returns_deserializer_instance(MessageFormat) > [4] BYTES FAILED
    java.lang.NullPointerException at MessageFormatSerializationFactoryTest.java:79

AuthConfigTest > testSaslAuthConfigWithPlainText() FAILED
    java.lang.ClassCastException at AuthConfigTest.java:56

AuthConfigTest > testSaslAuthConfigWithMskIam() FAILED
    java.lang.ClassCastException at AuthConfigTest.java:56

AuthConfigTest > testSaslAuthConfigWithOAuth() FAILED
    java.lang.ClassCastException at AuthConfigTest.java:56

AuthConfigTest > testPlainTextAuthConfig() FAILED
    java.lang.ClassCastException at AuthConfigTest.java:56

CommonTopicConfigTest > testConfigValues_from_yaml() FAILED
    java.lang.ClassCastException at CommonTopicConfigTest.java:41

CommonTopicConfigTest > test_topicsConfig_not_null() FAILED
    java.lang.ClassCastException at CommonTopicConfigTest.java:41

CommonTopicConfigTest > testConfigValues_default() FAILED
    java.lang.ClassCastException at CommonTopicConfigTest.java:41

CommonTopicConfigTest > testConfigValues_from_yaml_not_null() FAILED
    java.lang.ClassCastException at CommonTopicConfigTest.java:41

KmsConfigTest > toCredentialsOptions_returns_options_with_correct_values() FAILED
    java.lang.IllegalArgumentException at KmsConfigTest.java:33
        Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException at KmsConfigTest.java:33

MskBrokerConnectionTypeTest > fromTypeValue(MskBrokerConnectionType) > [1] null FAILED
    java.lang.NullPointerException at MskBrokerConnectionTypeTest.java:19

MskBrokerConnectionTypeTest > fromTypeValue(MskBrokerConnectionType) > [2] null FAILED
    java.lang.NullPointerException at MskBrokerConnectionTypeTest.java:19

MskBrokerConnectionTypeTest > fromTypeValue(MskBrokerConnectionType) > [3] null FAILED
    java.lang.NullPointerException at MskBrokerConnectionTypeTest.java:19

OAuthConfigTest > assertNotNullForConfigs() FAILED
    java.lang.ClassCastException at OAuthConfigTest.java:49

OAuthConfigTest > assertConfigValues() FAILED
    java.lang.ClassCastException at OAuthConfigTest.java:49

OAuthConfigTest > testConfig() FAILED
    java.lang.ClassCastException at OAuthConfigTest.java:49

PlainTextAuthConfigTest > testConfigValues() FAILED
    java.lang.ClassCastException at PlainTextAuthConfigTest.java:35

SchemaConfigTest > test_schemaConfig_not_null() FAILED
    java.lang.ClassCastException at SchemaConfigTest.java:37

SchemaConfigTest > test_schemaConfig_values() FAILED
    java.lang.ClassCastException at SchemaConfigTest.java:37

KafkaCustomConsumerTest > testJsonDeserializationErrorWithAcknowledgements() FAILED
    java.lang.IllegalAccessError at KafkaCustomConsumerTest.java:162

KafkaCustomConsumerTest > testAwsGlueErrorWithAcknowledgements() FAILED
    java.lang.IllegalAccessError at KafkaCustomConsumerTest.java:162

KafkaCustomConsumerTest > testPlainTextConsumeRecordsWithAcknowledgements() FAILED
    java.lang.IllegalAccessError at KafkaCustomConsumerTest.java:162

KafkaCustomConsumerTest > testJsonConsumeRecords() FAILED
    java.lang.IllegalAccessError at KafkaCustomConsumerTest.java:162

KafkaCustomConsumerTest > testPlainTextConsumeRecordsWithNegativeAcknowledgements() FAILED
    java.lang.IllegalAccessError at KafkaCustomConsumerTest.java:162

KafkaCustomConsumerTest > testPlainTextConsumeRecords() FAILED
    java.lang.IllegalAccessError at KafkaCustomConsumerTest.java:162

TopicPartitionCommitTrackerTest > test(List) > [1] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [2] [9, 8, 7, 6, 5, 4, 3, 2, 1, 0] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [3] [1, 0, 2, 3, 5, 9, 4, 8, 6, 7] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [4] [5, 7, 4, 0, 2, 1, 3, 9, 8, 6] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [5] [1, 6, 2, 5, 7, 4, 0, 9, 8, 3] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [6] [1, 2, 6, 5, 3, 9, 4, 7, 0, 8] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [7] [8, 4, 0, 6, 3, 1, 7, 2, 5, 9] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [8] [0, 2, 5, 7, 1, 8, 6, 3, 4, 9] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [9] [3, 8, 2, 6, 7, 1, 5, 0, 9, 4] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [10] [4, 9, 2, 3, 7, 8, 0, 1, 5, 6] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [11] [0, 6, 8, 1, 5, 9, 4, 7, 2, 3] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > test(List) > [12] [9, 7, 0, 1, 2, 8, 5, 6, 3, 4] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:51

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [1] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [2] [9, 8, 7, 6, 5, 4, 3, 2, 1, 0] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [3] [1, 4, 7, 5, 0, 6, 8, 2, 9, 3] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [4] [9, 6, 3, 4, 2, 8, 0, 5, 1, 7] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [5] [1, 6, 2, 0, 8, 5, 7, 4, 9, 3] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [6] [3, 2, 4, 0, 5, 1, 7, 8, 9, 6] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [7] [8, 2, 6, 4, 3, 5, 7, 1, 9, 0] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [8] [8, 6, 9, 7, 1, 0, 4, 2, 5, 3] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [9] [3, 1, 8, 2, 6, 5, 4, 9, 7, 0] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [10] [6, 1, 2, 8, 9, 5, 4, 0, 7, 3] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [11] [6, 9, 1, 5, 7, 4, 3, 2, 8, 0] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

TopicPartitionCommitTrackerTest > testNonZeroOffsets(List) > [12] [9, 8, 0, 6, 7, 4, 5, 2, 3, 1] FAILED
    java.lang.AssertionError at TopicPartitionCommitTrackerTest.java:75

KafkaClusterConfigTest > testConfigWithTestExtension() FAILED
    java.lang.annotation.AnnotationFormatError at KafkaClusterConfigTest.java:40

KafkaCustomProducerTest > testGetGenericRecord() FAILED
    java.lang.ExceptionInInitializerError at KafkaCustomProducerTest.java:249
        Caused by: java.lang.NullPointerException at KafkaCustomProducerTest.java:249

KafkaCustomProducerTest > producePlainTextRecords() FAILED
    java.lang.NullPointerException at KafkaCustomProducer.java:112

KafkaCustomProducerTest > producePlainTextRecords_callbackException() FAILED
    java.lang.NullPointerException at KafkaCustomProducer.java:112

KafkaCustomProducerTest > validateSchema() FAILED
    com.github.fge.jsonschema.core.exceptions.ProcessingException at KafkaCustomProducerTest.java:261

KafkaCustomProducerTest > produceRawDataTest() FAILED
    java.lang.NullPointerException at KafkaCustomProducerTest.java:105

KafkaCustomProducerTest > producePlainTextRecords_sendError() FAILED
    java.lang.NullPointerException at KafkaCustomProducer.java:112

KafkaCustomProducerTest > produceJsonRecordsTest() FAILED
    java.lang.NullPointerException at KafkaCustomProducer.java:112

KafkaCustomProducerTest > produceAvroRecordsTest() FAILED
    java.lang.NoClassDefFoundError at KafkaCustomProducerTest.java:227

KafkaCustomProducerTest > produceRawData_sendError() FAILED
    org.mockito.exceptions.misusing.UnfinishedStubbingException at KafkaCustomProducerTest.java:87

DLQSinkTest > testPerform() FAILED
    java.lang.ClassCastException at DLQSinkTest.java:68

KafkaSinkConfigTest > testDLQConfiguration() FAILED
    java.util.NoSuchElementException at KafkaSinkConfigTest.java:97

KafkaSinkTest > doOutputExceptionTest() FAILED
    java.lang.ClassCastException at KafkaSinkTest.java:105

KafkaSinkTest > doOutputTest() FAILED
    java.lang.ClassCastException at KafkaSinkTest.java:105

KafkaSinkTest > doInitializeNullPointerExceptionTest() FAILED
    java.lang.ClassCastException at KafkaSinkTest.java:105

KafkaSinkTest > isReadyTest() FAILED
    java.lang.ClassCastException at KafkaSinkTest.java:105

KafkaSinkTest > shutdownTest() FAILED
    java.lang.ClassCastException at KafkaSinkTest.java:105

KafkaSinkTest > shutdownExceptionTest() FAILED
    java.lang.ClassCastException at KafkaSinkTest.java:105

KafkaSinkTest > doOutputTestForAutoTopicCreate() FAILED
    java.lang.ClassCastException at KafkaSinkTest.java:105

KafkaSinkTest > doInitializeTest() FAILED
    java.lang.ClassCastException at KafkaSinkTest.java:105

KafkaSinkTest > doOutputEmptyRecordsTest() FAILED
    java.lang.ClassCastException at KafkaSinkTest.java:105

KafkaSourceConfigTest > test_topics_not_null() FAILED
    java.lang.ClassCastException at KafkaSourceConfigTest.java:47

KafkaSourceConfigTest > test_kafka_config_not_null() FAILED
    java.lang.ClassCastException at KafkaSourceConfigTest.java:47

KafkaSourceConfigTest > test_setters() FAILED
    java.lang.ClassCastException at KafkaSourceConfigTest.java:47

KafkaSourceConfigTest > test_bootStrapServers_not_null() FAILED
    java.lang.ClassCastException at KafkaSourceConfigTest.java:47

KafkaSourceTest > test_kafkaSource_basicFunctionality() FAILED
    java.lang.RuntimeException at KafkaSourceTest.java:150
        Caused by: java.lang.NullPointerException at KafkaSourceTest.java:150

KafkaSourceTest > test_kafkaSource_retry_consumer_create() FAILED
    java.lang.RuntimeException at KafkaSource.java:155
        Caused by: java.lang.NullPointerException at KafkaSourceTest.java:165

AuthenticationPropertyConfigurerTest > testSetSaslPlainTextProperties() FAILED
    java.lang.ClassCastException at AuthenticationPropertyConfigurerTest.java:34

AuthenticationPropertyConfigurerTest > testSetSaslSslProperties() FAILED
    java.lang.ClassCastException at AuthenticationPropertyConfigurerTest.java:34

AuthenticationPropertyConfigurerTest > testSetSaslOauthProperties() FAILED
    java.lang.ClassCastException at AuthenticationPropertyConfigurerTest.java:34

AuthenticationTypeTest > getAuthTypeByName(AuthenticationType) > [1] plaintext FAILED
    java.lang.NullPointerException at AuthenticationTypeTest.java:17

AuthenticationTypeTest > getAuthTypeByName(AuthenticationType) > [2] ssl FAILED
    java.lang.NullPointerException at AuthenticationTypeTest.java:17

AuthenticationTypeTest > getAuthTypeByName(AuthenticationType) > [3] oauth FAILED
    java.lang.NullPointerException at AuthenticationTypeTest.java:17

KafkaTopicConsumerMetricsTests > KafkaTopicMetricTest_checkMetricUpdates(int) > [1] 1 FAILED
    java.lang.NullPointerException at KafkaTopicConsumerMetricsTests.java:211

KafkaTopicConsumerMetricsTests > KafkaTopicMetricTest_checkMetricUpdates(int) > [2] 5 FAILED
    java.lang.NullPointerException at KafkaTopicConsumerMetricsTests.java:211

KafkaTopicConsumerMetricsTests > KafkaTopicMetricTest_checkMetricUpdates(int) > [3] 10 FAILED
    java.lang.NullPointerException at KafkaTopicConsumerMetricsTests.java:211

KafkaTopicProducerMetricsTests > KafkaTopicMetricTest_checkMetricUpdates(int) > [1] 1 FAILED
    java.lang.NullPointerException at KafkaTopicProducerMetricsTests.java:169

KafkaTopicProducerMetricsTests > KafkaTopicMetricTest_checkMetricUpdates(int) > [2] 5 FAILED
    java.lang.NullPointerException at KafkaTopicProducerMetricsTests.java:169

KafkaTopicProducerMetricsTests > KafkaTopicMetricTest_checkMetricUpdates(int) > [3] 10 FAILED
    java.lang.NullPointerException at KafkaTopicProducerMetricsTests.java:169

SinkPropertyConfigurerTest > testGetProducerPropertiesForPlainText() FAILED
    java.lang.ClassCastException at SinkPropertyConfigurerTest.java:43

SinkPropertyConfigurerTest > testGetProducerPropertiesForNoSerde() FAILED
    java.lang.ClassCastException at SinkPropertyConfigurerTest.java:43

SinkPropertyConfigurerTest > testGetProducerPropertiesForAvro() FAILED
    java.lang.ClassCastException at SinkPropertyConfigurerTest.java:43

SinkPropertyConfigurerTest > testGetProducerPropertiesForJson() FAILED
    java.lang.ClassCastException at SinkPropertyConfigurerTest.java:43

258 tests completed, 132 failed
```

https://github.com/opensearch-project/data-prepper/actions/runs/7479248734/job/20362415558?pr=3937

**Comment by dlvenable** [comment]
Seen today:

```
ExportPartitionWorkerTest > testProcessPartitionSuccess(String) > [1] test.collection|0|1|java.lang.Integer FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at ExportPartitionWorkerTest.java:120
```

**Comment by dlvenable** [comment]
Seen today:

```
HistogramAggregateActionTests > testHistogramAggregateOTelFormatWithStartAndEndTimesInTheEvent(int) > [1] 10 FAILED
    java.lang.AssertionError at HistogramAggregateActionTests.java:370
```

**Comment by dlvenable** [comment]
Some investigation on `AggregateProcessorIT`.

```
[2] 15.0

java.lang.AssertionError: 
Expected: a numeric value within <1.0> of <3000.0>
     but: <2994.0> differed by <5.0> more than delta <1.0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.opensearch.dataprepper.plugins.processor.aggregate.AggregateProcessorIT.aggregateWithPercentSamplerAction(AggregateProcessorIT.java:292)
```

This assertion is failing:

```
assertThat((double)allowedEventsCount.get(), closeTo(NUM_THREADS * NUM_EVENTS_PER_BATCH * testPercent/100, 1.0));
```

**Comment by dlvenable** [comment]
A new failure:

```
LambdaSinkServiceTest > lambda_sink_test_batch_enabled() FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at LambdaSinkServiceTest.java:316
```

**Comment by dlvenable** [comment]
New failure: > Task :data-prepper-plugins:log-generator-source:test

LogGeneratorSourceTest > GIVEN_logGeneratorSourceAndBlockingBuffer_WHEN_reachedLimit_THEN_stopsWritingToBuffer() FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at LogGeneratorSourceTest.java:115

**Comment by dlvenable** [comment]
Another AggregateProcessorIT:

```
AggregateProcessorIT > aggregateWithCountAggregateActionWithCondition() > repetition 2 of 2 FAILED
    java.lang.AssertionError at AggregateProcessorIT.java:439
```

**Comment by dlvenable** [comment]
RDS now has a flaky test:

```
> Task :data-prepper-plugins:rds-source:test

ExportSchedulerTest > test_shutDown() FAILED
    org.mockito.exceptions.verification.NoInteractionsWanted at ExportSchedulerTest.java:271
```

https://github.com/opensearch-project/data-prepper/actions/runs/11172396206/job/31058770072?pr=5021

**Comment by oeyh** [comment]
Truncate processor test. https://github.com/opensearch-project/data-prepper/actions/runs/11277679724/job/31364395140?pr=5016

```
> Task :data-prepper-plugins:truncate-processor:test

TruncateProcessorConfigTests > testInvalidConfiguration_StartAt_Length_Negative() FAILED
    org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
```

**Comment by dlvenable** [comment]
One of the tests may have had its assertion line moved:

```
PipelinesWithAcksIT > two_pipelines_with_multiple_records() FAILED
    java.lang.NullPointerException at PipelinesWithAcksIT.java:110
```

**Comment by dlvenable** [comment]
```
DataFileSchedulerTest > test_shutdown() FAILED
    org.mockito.exceptions.verification.NoInteractionsWanted: 
    No interactions wanted here:
    -> at org.opensearch.dataprepper.plugins.source.rds.export.DataFileSchedulerTest.test_shutdown(DataFileSchedulerTest.java:197)
    But found this interaction on mock 'sourceCoordinator':
    -> at org.opensearch.dataprepper.plugins.source.rds.export.DataFileScheduler.run(DataFileScheduler.java:107)
    Actually, above is the only interaction with this mock.
```

**Comment by dlvenable** [comment]
```
PipelinesWithAcksIT > simple_pipeline_with_single_record() FAILED
    java.lang.NullPointerException at PipelinesWithAcksIT.java:79
```

https://github.com/opensearch-project/data-prepper/actions/runs/12371897788/job/35401071818?pr=5268

**Comment by dlvenable** [comment]
```
GrpcRetryInfoCalculatorTest > testResetAfterDelayWearsOff() FAILED
    java.lang.AssertionError: 
    Expected: <2000000>
         but: was <1000000>
```

https://github.com/opensearch-project/data-prepper/actions/runs/12677623107/job/35393227951?pr=5316

**Comment by dlvenable** [comment]
```
ExportSchedulerTest > test_export_run() FAILED
    org.mockito.exceptions.verification.TooFewActualInvocations: 
    coordinator.getPartition(
        "EXPORT-9d4ad72c-1ed6-4ff3-b203-668ddecec561"
    );
    Wanted 3 times:
    -> at org.opensearch.dataprepper.plugins.mongo.export.ExportSchedulerTest.test_export_run(ExportSchedulerTest.java:173)
    But was 2 times:
    -> at org.opensearch.dataprepper.plugins.mongo.export.ExportScheduler.run(ExportScheduler.java:79)
    -> at org.opensearch.dataprepper.plugins.mongo.export.ExportScheduler.run(ExportScheduler.java:83)
```

https://github.com/opensearch-project/data-prepper/actions/runs/12699965937/job/35401719449?pr=5321

**Comment by graytaylor0** [comment]
```

OTelTraceRawProcessorTest > traceGroupCacheMaxSize_provides_an_upper_bound(long, int) > [1] 1, 4 FAILED
    java.lang.AssertionError: 
    Expected: <4>
         but: was <6>
```

**Comment by graytaylor0** [comment]
```
> Task :data-prepper-plugins:mongodb:test
128 tests completed, 1 failed

> Task :data-prepper-plugins:mongodb:test FAILED
```

**Comment by graytaylor0** [comment]
```
Task :data-prepper-plugins:rds-source:test

StreamSchedulerTest > test_shutdown() FAILED
    org.mockito.exceptions.verification.NoInteractionsWanted: 
    No interactions wanted here:
    -> at org.opensearch.dataprepper.plugins.source.rds.stream.StreamSchedulerTest.test_shutdown(StreamSchedulerTest.java:126)
    But found this interaction on mock 'sourceCoordinator':
    -> at org.opensearch.dataprepper.plugins.source.rds.stream.StreamScheduler.run(StreamScheduler.java:70)
    Actually, above is the only interaction with this mock.
```

**Comment by graytaylor0** [comment]
```

> Task :data-prepper-plugins:rds-source:test

LeaderSchedulerTest > test_shutDown() FAILED
    org.mockito.exceptions.verification.NoInteractionsWanted: 
    No interactions wanted here:
    -> at org.opensearch.dataprepper.plugins.source.rds.leader.LeaderSchedulerTest.test_shutDown(LeaderSchedulerTest.java:138)
    But found this interaction on mock 'sourceCoordinator':
    -> at org.opensearch.dataprepper.plugins.source.rds.leader.LeaderScheduler.run(LeaderScheduler.java:67)
    Actually, above is the only interaction with this mock.
```
