### ISSUE TITLE
[BUG] Cannot get view in DashBoard - jaeger-hotrod

### ISSUE THREAD

**Issue by balamir1979** [opensearch-project/data-prepper#3499]
I get a x_content_parse_exception while triying .\examples\jaeger-hotrod Steps to reproduce the behavior:
1. Go to localhost:8080 and click some buttons on Hot ROD page. 2. Open http://127.0.0.1:5601/app/observability-traces , select Data-Prepper and click refresh button
3. See Error (details in opensearch-dasboard container) /***********
{"statusCode":200,"responseTime":8,"contentLength":9},"message":"POST /api/observability/trace_analytics/query 200 8ms - 9.0B"}
StatusCodeError: [parsing_exception] [term] query does not support [dispatchConfig], with { line=1 & col=328 } at respond (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:349:15) at checkRespForFailure (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:306:7) at HttpConnector. (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/connectors/http.js:173:7) at IncomingMessage.wrapper (/usr/share/opensearch-dashboards/node_modules/lodash/lodash.js:4991:19) at IncomingMessage.emit (node:events:525:35) at IncomingMessage.emit (node:domain:489:12) at endReadableNT (node:internal/streams/readable:1359:12) at processTicksAndRejections (node:internal/process/task_queues:82:21) { status: 400, displayName: 'BadRequest', path: '/otel-v1-apm-span-*/_search', query: { size: 0 }, body: { error: { root_cause: [Array], type: 'x_content_parse_exception', reason: '[1:328] [bool] failed to parse field [must]', caused_by: [Object] }, status: 400 }, statusCode: 400, response: '{"error":{"root_cause":[{"type":"parsing_exception","reason":"[term] query does not support [dispatchConfig]","line":1,"col":328}],"type":"x_content_parse_exception","reason":"[1:328] [bool] failed to parse field [must]","caused_by":{"type":"parsing_exception","reason":"[term] query does not support [dispatchConfig]","line":1,"col":328}},"status":400}', toString: [Function (anonymous)], toJSON: [Function (anonymous)]
}
/*********** I expected to see : some data on this page If applicable, add screenshots to help explain your problem. **Environment (please complete the following information):** - OS: [e.g. Ubuntu 20.04 LTS] - Version [e.g. 22] **Additional context**
Add any other context about the problem here. My Environment is Windows 10 and i disabled security features in configurations. I attached all releated files as zip file.
[files.zip](https://github.com/opensearch-project/data-prepper/files/12887422/files.zip)

**Comment by balamir1979** [comment]
If I pull the files from the repository and run docker-compose directly, I get the following errors: 


**data-prepper** | 2023-10-13T13:11:35,339 [service-map-pipeline-sink-worker-4-thread-1] WARN org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Failed to initialize OpenSearch sink, retrying: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors

**jaeger-hotrod-jaeger-hot-rod-1**  | 2023/10/13 13:12:34 traces export: Post "http://localhost:4318/v1/traces": dial tcp 127.0.0.1:4318: connect: connection refused

**Comment by dlvenable** [comment]
@balamir1979 , I am also seeing something similar. There may be some issues with the versions of the different dependencies.

You may wish to try out the trace-analytics-sample-app instead. It is working for me.

https://github.com/opensearch-project/data-prepper/tree/main/examples/trace-analytics-sample-app

**Comment by kunalsingthakur** [comment]
same for me

**Comment by linghengqian** [comment]
- I clarified this in #4972. All TLS certificates for opensearch's Docker Image point to `https://node-0.example.com`, and the TLS certificates have a very long validity period. If you did not switch the `hostname` of the opensearch Docker Container to `node-0.example.com`, you need to consider letting Data Prepper ignore the TLS certification of the opensearch Docker Container, or generate a separate TLS certificate for OpenSearch that is intuitive and has a shorter validity period.
