### ISSUE TITLE
[BUG] Serialization error during peer-forwarding

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3981]
**Describe the bug**

Peer forwarding is unable to serialize events.

```
2024-01-17T23:51:34.293 [test-pipeline-processor-worker-1-thread-1] WARN  org.opensearch.dataprepper.peerforwarder.RemotePeerForwarder - Unable to submit request for forwarding, processing locally.
java.lang.RuntimeException: java.io.NotSerializableException: java.lang.ref.WeakReference
  at org.opensearch.dataprepper.peerforwarder.client.PeerForwarderClient.getSerializedJsonBytes(PeerForwarderClient.java:87) ~[data-prepper-core-2.6.1.jar:?]
  at org.opensearch.dataprepper.peerforwarder.client.PeerForwarderClient.serializeRecordsAndSendHttpRequest(PeerForwarderClient.java:71) ~[data-prepper-core-2.6.1.jar:?]
  at org.opensearch.dataprepper.peerforwarder.RemotePeerForwarder.forwardRecordsForIp(RemotePeerForwarder.java:267) ~[data-prepper-core-2.6.1.jar:?]
Caused by: java.io.NotSerializableException: java.lang.ref.WeakReference
  at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175) ~[?:?]
  at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543) ~[?:?]
  at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500) ~[?:?]
  at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1423) ~[?:?]
  at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1169) ~[?:?]
  at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1543) ~[?:?]
  at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1500) ~[?:?]
  ... 14 more
```

**To Reproduce**

1. Configure Data Prepper to use peer-forwarding
2. Create a pipeline with an `aggregate` processor.
3. Run multiple Data Prepper instances
4. Inject data that will need to route across peers

 
**Expected behavior**

One Data Prepper node should be able to serialize and send the data to the other Data Prepper node.

**Environment (please complete the following information):**
 - Data Prepper: 2.6.1

**Comment by dlvenable** [comment]
I believe that the issue is we are trying to serialize the `EventHandle`:

https://github.com/opensearch-project/data-prepper/blob/6e921ad5bb1d709703651d9574cf1adc6f5c7555/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java#L71

It clearly has a `WeakReference` which we see in the logs above.

https://github.com/opensearch-project/data-prepper/blob/d3acfa72009a78202b44445b1f73792813dc7635/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/DefaultEventHandle.java#L20

We should skip the `eventHandle` during serialization.
