### ISSUE TITLE
Add support for BigDecimal in ConvertType processor

### ISSUE THREAD

**Issue by engechas** [opensearch-project/data-prepper#4316]
**Is your feature request related to a problem? Please describe.**
When using DDB source, some of the incoming data gets typed as BigDecimal. This type is not supported by the ConvertEntries processor which results in the below exception
```
Unable to convert key: ****** with value: ****** to ******
java.lang.IllegalArgumentException: Unsupported type conversion. Source class: class java.math.BigDecimal
	at org.opensearch.dataprepper.typeconverter.IntegerConverter.convert(IntegerConverter.java:22) ~[data-prepper-api-2.6.1.jar:?]
	at org.opensearch.dataprepper.typeconverter.IntegerConverter.convert(IntegerConverter.java:8) ~[data-prepper-api-2.6.1.jar:?]
 at org.opensearch.dataprepper.plugins.processor.mutateevent.ConvertEntryTypeProcessor.doExecute(ConvertEntryTypeProcessor.java:68) ~[mutate-event-processors-2.6.1.jar:?]
```

**Describe the solution you'd like**
BigDecimal should be added to the supported conversion types

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by kkondaka** [comment]
For now, if the values are small enough to fit in long/int, conversion to String should work (and if needed, convert it back to integer or long) as a work-around

**Comment by Utkarsh-Aga** [comment]
Hello @engechas @kkondaka , 
Can I work on raising the PR for this ?

**Comment by dlvenable** [comment]
@Utkarsh-Aga , That would be great. It would be quite similar to the work you did in #4359.

**Comment by Utkarsh-Aga** [comment]
Sure, Thanks.
I would work on raising the PR for this.
