### ISSUE TITLE
[BUG] Failed to decompress snappy file in S3 source

### ISSUE THREAD

**Issue by guanlinz** [opensearch-project/data-prepper#4406]
## Configuration File:
```
s3-ingestion-pipeline:
  source:
    s3:
      codec:
        newline:
      compression: "snappy" 
      aws:
        region: "cn-north-1"
      scan:
        buckets:
          - bucket:
              name: "bucket"
              filter:
                include_prefix:
                  - "etl/snappy_input/"

  sink:
    - opensearch:
```

## Error msg:
```
2024-04-10T14:06:10,222 [Thread-2] ERROR org.opensearch.dataprepper.plugins.source.s3.ScanObjectWorker - Error while process the parseS3Object. 
java.io.IOException: FAILED_TO_UNCOMPRESS(5)
        at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:112) ~[snappy-java-1.1.10.5.jar:1.1.10.5]
        at org.xerial.snappy.SnappyNative.rawUncompress(Native Method) ~[snappy-java-1.1.10.5.jar:1.1.10.5]
        at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:504) ~[snappy-java-1.1.10.5.jar:1.1.10.5]
        at org.xerial.snappy.Snappy.uncompress(Snappy.java:543) ~[snappy-java-1.1.10.5.jar:1.1.10.5]
        at org.xerial.snappy.SnappyInputStream.readFully(SnappyInputStream.java:165) ~[snappy-java-1.1.10.5.jar:1.1.10.5]
        at org.xerial.snappy.SnappyInputStream.readHeader(SnappyInputStream.java:117) ~[snappy-java-1.1.10.5.jar:1.1.10.5]
        at org.xerial.snappy.SnappyInputStream.<init>(SnappyInputStream.java:77) ~[snappy-java-1.1.10.5.jar:1.1.10.5]
        at org.xerial.snappy.SnappyInputStream.<init>(SnappyInputStream.java:61) ~[snappy-java-1.1.10.5.jar:1.1.10.5]
        at org.opensearch.dataprepper.plugins.codec.SnappyDecompressionEngine.createInputStream(SnappyDecompressionEngine.java:18) ~[common-2.7.0.jar:?]
        at org.opensearch.dataprepper.model.codec.InputCodec.parse(InputCodec.java:42) ~[data-prepper-api-2.7.0.jar:?]
        at org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker.doParseObject(S3ObjectWorker.java:99) ~[s3-source-2.7.0.jar:?]
        at org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker.lambda$parseS3Object$0(S3ObjectWorker.java:66) ~[s3-source-2.7.0.jar:?]
        at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129) ~[micrometer-core-1.11.5.jar:1.11.5]
        at org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker.parseS3Object(S3ObjectWorker.java:65) ~[s3-source-2.7.0.jar:?]
        at org.opensearch.dataprepper.plugins.source.s3.ScanObjectWorker.processS3Object(ScanObjectWorker.java:178) [s3-source-2.7.0.jar:?]
        at org.opensearch.dataprepper.plugins.source.s3.ScanObjectWorker.startProcessingObject(ScanObjectWorker.java:153) [s3-source-2.7.0.jar:?]
        at org.opensearch.dataprepper.plugins.source.s3.ScanObjectWorker.run(ScanObjectWorker.java:101) [s3-source-2.7.0.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
2024-04-10T14:06:10,227 [Thread-2] INFO  org.opensearch.dataprepper.plugins.source.s3.S3ScanPartitionCreationSupplier - Single S3 scan has already been completed
```
But the file is generated and produced by Glue Studio, so i don't think there is something wrong with the snappy file

## Version used
https://gallery.ecr.aws/opensearchproject/data-prepper

**Comment by dlvenable** [comment]
@guanlinz , If you have some steps you could share to generate the file that could help us debug this. Data Prepper should support Snappy, but perhaps there are certain scenarios that the code doesn't handle currently.
