### ISSUE TITLE
Clear and Compact User Error Messages

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#656]
**Is your feature request related to a problem? Please describe.**

When Data Prepper fails due to a user error, Data Prepper outputs a stack trace. The user of Data Prepper must make sense of this stack trace to know how to resolve the error. I am including a sample stack trace as additional context at the bottom of the issue.

**Describe the solution you'd like**

For user errors, return a cleaner message which provides more descriptive context.

```
FAILURE

Where:
Failed to parse the configuration file pipelines.yaml. Unable to parse pipeline, simple-test-pipeline.

Why:
Invalid configuration, at least one sink is required

For more help, visit the project page: https://github.com/opensearch-project/data-prepper
```

**Scope**

Unexpected failures in Data Prepper Core and in plugins should still result in stack trace output. When these unexpected scenarios occur, they are likely bugs and stack traces will help track them down.

**Proposed Approach**

Update Data Prepper API to include specific exceptions which indicate that a user errors has occurred. In Data Prepper Core, catch these types of exceptions and then wrap them in an outer exception which has additional context.

An example is plugin configuration errors. Plugins can throw a standardized exception - perhaps `InvalidPluginConfigurationException`. The pipeline parsing code can then catch that specific exception and wrap it into an exception which includes additional context and indicates that the exception is user-related. Finally, that exception is caught in `DataPrepperExecute` and used to print out the improved user message.

**Help Page**

The example output above refers users to a specific web page for help. It may also be valuable to have a single page dedicated to helping users. It might point to the documentation, suggest the forums, and include a link to submit a bug report.

For example:

```
For more help, visit the project page: https://github.com/opensearch-project/data-prepper/docs/help.md
```

**Additional context**

```
Exception in thread "main" com.amazon.dataprepper.parser.ParseException: Failed to parse the configuration file pipelines.yaml
	at com.amazon.dataprepper.parser.PipelineParser.parseConfiguration(PipelineParser.java:75)
	at com.amazon.dataprepper.DataPrepper.execute(DataPrepper.java:129)
	at com.amazon.dataprepper.DataPrepperExecute.main(DataPrepperExecute.java:33)
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.amazon.dataprepper.parser.model.PipelineConfiguration`, problem: Invalid configuration, at least one sink is required
 at [Source: (File); line: 6, column: 1] (through reference chain: java.util.LinkedHashMap["simple-test-pipeline"])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2047)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:587)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:610)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:293)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:288)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:518)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3515)
	at com.amazon.dataprepper.parser.PipelineParser.parseConfiguration(PipelineParser.java:58)
	... 2 more
Caused by: java.lang.IllegalArgumentException: Invalid configuration, at least one sink is required
	at com.amazon.dataprepper.parser.model.PipelineConfiguration.getSinksFromConfiguration(PipelineConfiguration.java:107)
	at com.amazon.dataprepper.parser.model.PipelineConfiguration.<init>(PipelineConfiguration.java:45)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:128)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:291)
	... 15 more
```

**Comment by graytaylor0** [comment]
I think this approach makes a lot of sense in regard to invalid configuration, and would save users the pain of having to sift through the stack trace here. However, in non-standard cases outside of configuration errors, it is hard to see a widespread use of this. But if we provided APIs to plugin creators that lets them wrap their own custom exceptions into this format, there are likely places where it would be used.

**Comment by dlvenable** [comment]
I do believe the scope of this would probably be limited to "configuration" errors because that is what the user of Data Prepper controls. So this could be a problem in the data-prepper-config.yaml, the pipeline.yaml, or with how Data Prepper was called (e.g. no arguments or too many arguments).

I'm not even sure if plugins will need this because if a plugin implements the JSR-303/JSR-380 bean validation, then configuration errors would be covered by the work for Data Prepper core. But, if we do find a concrete need to extend this behavior to plugins, we could add it then.
